const userData = {
  items: [
    {
      id: 0,
      title: "Тепловой шкаф henny penny",
      description: "Холодосы",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 1,
      title: "Картофельный бин fabristeel",
      description: "Бины",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "Тостер вертикальный prince castle",
      description: "Тостеры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 3,
      title: "Открытая фритюрница henny penny",
      description: "фритюрницы",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "Закрытая жаровня Henny Penny PFE 500",
      description: "Жаровни",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "Набор термометр Atkins e32",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 6,
      title: "Термометр atkins e32",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "Щуп для термометра atkins",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 8,
      title: "Бабочка для термометра atkins",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 9,
      title: "Набор для анализа качества масла Testo",
      description: "Наборы",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 10,
      title: "Термодуй 3000",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 11,
      title: "Термодуй ultra",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 12,
      title: "Жаровня Winston K450",
      description: "Жаровни",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 13,
      title: "Комбомашина Carpigiani GK3 PS P",
      description: "Комбомашины",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },

  ],
};

export default userData;
