const userData = {
  items: [
    // {
    //   id: 0,
    //   title: "Тепловой шкаф henny penny",
    //   description: "Холодосы",
    //   imgUrl: "/4bxNEZY2P-M.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 1,
    //   title: "Картофельный бин fabristeel",
    //   description: "Бины",
    //   imgUrl: "/j2kT1IIXExc.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 2,
    //   title: "Тостер вертикальный prince castle",
    //   description: "Тостеры",
    //   imgUrl: "/GqslfkzEb5s.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 3,
    //   title: "Открытая фритюрница henny penny",
    //   description: "фритюрницы",
    //   imgUrl: "/r6IgSwatXI8.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 4,
    //   title: "Закрытая жаровня под давлением Henny Penny PFE 500",
    //   description: "Жаровни",
    //   imgUrl: "/sEtHOlWZlWY.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 5,
    //   title: "Набор термометр Atkins e32",
    //   description: "Термометры",
    //   imgUrl: "/eNqMUmJsLYU.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 6,
    //   title: "Термометр atkins e32",
    //   description: "Термометры",
    //   imgUrl: "/ZuYnk4flD2U.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 7,
    //   title: "Щуп для термометра atkins",
    //   description: "Термометры",
    //   imgUrl: "/37aXLOn4l-s.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 8,
    //   title: "Бабочка для термометра atkins",
    //   description: "Термометры",
    //   imgUrl: "/YSJh_WjvLOc.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 9,
    //   title: "Набор для анализа качества масла Testo",
    //   description: "Наборы",
    //   imgUrl: "/YSJh_WjvLOc.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 10,
    //   title: "Термодуй 3000",
    //   description: "Термометры",
    //   imgUrl: "/a-sxJOPgsmQ.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 11,
    //   title: "Термодуй ultra",
    //   description: "Термометры",
    //   imgUrl: "/xzkxy_B8Zkw.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 12,
    //   title: "Жаровня Winston K450",
    //   description: "Жаровни",
    //   imgUrl: "/XMC1qZgMBWY.jpg",
    //   quantity: 1,
    // },
    // {
    //   id: 13,
    //   title: "Комбомашина Carpigiani GK3 PS P",
    //   description: "Комбомашины",
    //   imgUrl: "/OFkvU65GDYo.jpg",
    //   quantity: 1,
    // },

    {
      id: 0,
      title: "Тепловой шкаф henny penny",
      description: "Холодосы",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 1,
      title: "Картофельный бин fabristeel",
      description: "Бины",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "Тостер вертикальный prince castle",
      description: "Тостеры",
      imgUrl: "/XMC1qZgMBWY.jpg",
      quantity: 1,
    },
    {
      id: 3,
      title: "Открытая фритюрница henny penny",
      description: "фритюрницы",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "Закрытая жаровня Henny Penny PFE 500",
      description: "Жаровни",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "Набор термометр Atkins e32",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 6,
      title: "Термометр atkins e32",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "Щуп для термометра atkins",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 8,
      title: "Бабочка для термометра atkins",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 9,
      title: "Набор для анализа качества масла Testo",
      description: "Наборы",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 10,
      title: "Термодуй 3000",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 11,
      title: "Термодуй ultra",
      description: "Термометры",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 12,
      title: "Жаровня Winston K450",
      description: "Жаровни",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },
    {
      id: 13,
      title: "Комбомашина Carpigiani GK3 PS P",
      description: "Комбомашины",
      imgUrl: "/holodos.jpg",
      quantity: 1,
    },

  ],
};

export default userData;
